### ISSUE TITLE
Publish changes

### ISSUE THREAD

**Issue by alexisvincent** [jspm/nodelibs-zlib#2]
A few of these node-libs have changes that havn't yet beed published to npm. Any chance that this could happen? @frederikschubert @guybedford

**Comment by frederikschubert** [comment]
I can publish a new version of the libs to npm if that is alright! @guybedford?

**Comment by guybedford** [comment]
Sure, a patch release to npm is welcome, just be sure not to tag it for GitHub as the Github stable tag must be 0.1.0 for jspm 0.16 users.

**Comment by guybedford** [comment]
I've pushed out a 0.2.1.

**Comment by alexisvincent** [comment]
@guybedford Most of the other libs also need to be pushed. Any chance this could be done?

Thanks for pushing this one!
